# -*- coding: utf-8 -*-
"""Selamat Datang di Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math

# Menerima input dari user
a = int(input("Masukkan bilangan bulat pertama (a): "))
b = int(input("Masukkan bilangan bulat kedua (b): "))

# Melakukan perhitungan
jumlah = a + b
selisih = b - a
hasil_kali = a * b
sisa_bagi = a % b
pembagian = a / b if b != 0 else "Tidak bisa membagi dengan nol"
log_a = math.log10(a) if a > 0 else "Logaritma tidak terdefinisi untuk nilai nol atau negatif"
a_pangkat_b = a ** b

# Menampilkan hasil
print("Jumlah a dan b: ", jumlah)
print("Selisih antara b dengan a: ", selisih)
print("Hasil kali a dan b: ", hasil_kali)
print("Sisa pembagian a dengan b: ", sisa_bagi)
print("Pembagian a dengan b: ", pembagian)
print("Hasil dari log(a): ", log_a)
print("a pangkat b: ", a_pangkat_b)

# Program untuk menghitung luas ruangan

# Input panjang dan lebar dari user
panjang = float(input("Masukkan panjang ruangan: "))
lebar = float(input("Masukkan lebar ruangan: "))

# Input satuan dari user
satuan = input("Masukkan satuan (meter/inci): ").lower()

# Process: Menghitung luas berdasarkan satuan
if satuan == "meter":
    luas = panjang * lebar
    print(f"Luas ruangan adalah {luas} meter persegi.")
elif satuan == "inci":
    luas = panjang * lebar
    print(f"Luas ruangan adalah {luas} inci persegi.")
else:
    print("Satuan yang dimasukkan tidak valid. Harap masukkan 'meter' atau 'inci'.")